CXX=g++-4.7
CXXFLAGS=-I/usr/X11R6/include -L/usr/X11R6/lib -lGL -lGLEW -lglut -std=c++0x -g
simple-example : simple-example.cpp boids.cpp
display-example : display-example.cpp boids.cpp boidrenderer.cpp
