CXX=g++-4.7
CXXFLAGS=-I/usr/X11R6/include -L/usr/X11R6/lib -lGL -lGLEW -lglut -std=c++11 -fopenmp -O3 -march=native
simple-example : simple-example.cpp boids.hpp boids.cpp
display-example : display-example.cpp boids.hpp boids.cpp boidrenderer.cpp boidrenderer.hpp
